# SEO Values
title: The-Repo-Club
tagline: Home page for all things repo club
description: Home page for all things repo club
url: https://linuxrepos.org
read_time: true
words_per_minute: 200

# Site configurations
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: /:year/:month/:day/:title/

# Google Analytics ID
google_analytics:

# utterances
utterances: true

# GitHub Values
github:
  owner_name: The-Repo-Club
  owner_url: https://github.com/The-Repo-Club
  repository_url: https://github.com/The-Repo-Club/The-Repo-Club

show_header: true
remote_theme: "The-Repo-Club/The-Repo-Club"
