# SEO Values
title: The-Repo-Club
tagline: Home page for all things repo club
description: Home page for all things repo club
url: https://therepo.club/

# Site configurations
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# Google Analytics ID
google_analytics:

# disqus
disqus_short_name:

# GitHub Values
github:
  owner_name: The-Repo-Club
  owner_url: https://github.com/The-Repo-Club
  repository_url: https://github.com/The-Repo-Club/The-Repo-Club

show_downloads: false
show_forks: false
show_header: true
remote_theme: "The-Repo-Club/The-Repo-Club"
