description = "A minimalistic (minimalistcss) theme for bloggers"
features = [
  "minimalistic blog",
  "social icons",
  "editable colors",
]
homepage = "https://github.com/MinimalistCSS/minimalistcss.github.io"
license = "MIT"
licenselink = "https://github.com/MinimalistCSS/minimalistcss.github.io/blob/main/LICENSE"
name = "minimalistcss"
tags = ["blog", "minimalistic", "minimal", "responsive", "dark"]

[author]
homepage = "https://minimalistcss.github.io"
name = "MinimalistCSS"
